routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\ActivateController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ArticleController as BackendArticleController;
use App\Http\Controllers\Backend\ExhibitionController as BackendExhibitionController;
use App\Http\Controllers\Backend\GameController as BackendGameController;
use App\Http\Controllers\Backend\GenreController as BackendGenreController;
use App\Http\Controllers\Backend\PlatformController as BackendPlatformController;
use App\Http\Controllers\Backend\PublisherController as BackendPublisherController;
use App\Http\Controllers\Backend\RSSItemController;
use App\Http\Controllers\Backend\RSSItemController as BackendRSSItemController;
use App\Http\Controllers\Backend\RSSWebsiteController as BackendRSSWebsiteController;
use App\Http\Controllers\Backend\SerieController as BackendSerieController;
use App\Http\Controllers\Backend\UserController as BackendUserController;
use App\Http\Controllers\Backend\PageController as BackendPageController;
use App\Http\Controllers\DeveloperController;
use App\Http\Controllers\ExhibitionController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PlatformController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\RSSCrawlerController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin'], function() {

    $exceptShow = ['except' => [ 'show' ] ];

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('home');

    Route::resource('/articles', App\Http\Controllers\Backend\ArticleController::class);
    Route::resource('/developers', App\Http\Controllers\Backend\DeveloperController::class, $exceptShow);
    Route::resource('/exhibitions', BackendExhibitionController::class, $exceptShow);
    Route::post('/exhibitions/game/add', [BackendExhibitionController::class, 'save_exhibition_game']);
    Route::post('/exhibitions/game/update', [BackendExhibitionController::class, 'update_exhibition_game']);
    Route::resource('/games', BackendGameController::class, $exceptShow);
    Route::post('/games/ajax', [BackendGameController::class, 'ajax']);
    Route::resource('/genres', BackendGenreController::class, $exceptShow);
    Route::resource('/platforms', BackendPlatformController::class, $exceptShow);
    Route::resource('/publishers', BackendPublisherController::class, $exceptShow);
    Route::resource('/rssitems', BackendRSSItemController::class, $exceptShow);
    Route::resource('/rsswebsites', BackendRSSWebsiteController::class);
    Route::resource('/series', BackendSerieController::class)->parameters(['series' => 'serie']);;
    Route::resource('/users', BackendUserController::class, $exceptShow);
    Route::resource('/pages', BackendPageController::class)->parameters([
        'pages' => 'admin_pages'
    ]);

    Route::get('removeDuplicates', [RSSCrawlerController::class, 'removeDuplicates']);
    Route::get('games/recently-in-rss', [BackendGameController::class, 'recentlyInRSS']);
    Route::get('games/recently-in-rss/coupling', [BackendGameController::class, 'recentlyInRSSCoupling']);
    Route::get('games/find-publisher/{game}', [BackendGameController::class, 'findPublisher']);
    Route::get('games/find-developer/{game}', [BackendGameController::class, 'findDeveloper']);
    Route::get('games/create/{title}', [BackendGameController::class, 'create']);
    Route::get('games/enrich', [BackendGameController::class, 'enrich']);
    Route::get('/news', [BackendArticleController::class, 'index']);
    Route::get('publishers/create/{title}', [BackendPublisherController::class, 'create']);
    Route::get('rssitems/find-keywords', [BackendRSSItemController::class,'findKeywords']);
    Route::get('rssitems/suggest-game-title', [RSSCrawlerController::class, 'suggestGameTitle']);
    Route::get('rssitems/import',  [BackendRSSItemController::class,'import']);
    Route::get('rssitems/link',  [BackendRSSItemController::class,'link']);
    Route::get('rssitems/archive/{dateFrom}/{dateTo?}',  [BackendRSSItemController::class,'archive']);
});

// Sitemap
Route::get('/sitemap.xml', [SitemapController::class, 'index']);
Route::get('/sitemap', [SitemapController::class, 'index']);
Route::get('/sitemap/articles', [SitemapController::class, 'articles']);
Route::get('/sitemap/platforms', [SitemapController::class, 'platforms']);
Route::get('/sitemap/games', [SitemapController::class, 'games']);
Route::get('/sitemap/pages', [SitemapController::class, 'pages']);
Route::get('/rss', [SitemapController::class, 'rss']);

// Articles
Route::get('/news', [ArticleController::class, 'index']);
Route::get('/article/{article}', [ArticleController::class, 'show']);

// Publishers
Route::get('/publishers', [PublisherController::class, 'index']);
Route::get('/publishers/{publisher}', [PublisherController::class, 'show']);

// Developers
Route::get('/developers', [DeveloperController::class, 'index']);
Route::get('/developers/{developer}', [DeveloperController::class, 'show']);

// Platforms
Route::get('/platforms', [PlatformController::class, 'index']);
Route::get('/platforms/{platform}', [PlatformController::class, 'show']);


// Users
Route::get('/users/{user}', [UserController::class, 'show']);
Route::get('/members/{user}', [UserController::class, 'show']);

// Crawler
Route::get('/crawler/crawl', [RSSCrawlerController::class, 'crawl']);

// Games
Route::get('/games/list', [GameController::class, 'listed'])->name('games.list');
Route::get('/games/upcoming', [GameController::class, 'upcoming'])->name('games.upcoming');
Route::resource('/games', GameController::class)->only(['index', 'show'])->name('games', 'games.show');

// Search
Route::post('/search', [SearchController::class, 'index']);
Route::get('/search/{search}', [SearchController::class, 'results']);

// Authentication
Auth::routes();
Route::get('/validate', [ActivateController::class, 'index']);

// Other pages
Route::get('/', [PageController::class, 'home']);

// Very last routes for catching all pages
Route::get('/{exhibition}/lineup', [ExhibitionController::class, 'lineup']);
Route::get('/{exhibition}/exhibitors', [ExhibitionController::class, 'exhibitors']);

Route::get('/{slug}', function($slug) {

    $page = \App\Models\Page::where('slug', '=', $slug)->first();
    if($page != null) {
        $controller = app()->make('\App\Http\Controllers\PageController');
        return $controller->callAction('show', [$page]);
    }
    $exhibition = \App\Models\Exhibition::where('slug', '=', $slug)->first();
    if($exhibition != null) {
        $controller = app()->make('\App\Http\Controllers\ExhibitionController');
        return $controller->callAction('show', [$exhibition]);
    }

    if($exhibition == null && $page == null) {
        abort(404);
    }
});

app/Models/Game.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    use HasFactory;

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'games';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'released_at',
        'aliases',
    ];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    // Multiple games belong to multiple publishers
    // Many to many (to connect pivot table in DB)
    public function publishers()
    {
        return $this->belongsToMany(Publisher::class);
    }

    // Multiple games belong to multiple developers
    // Many to many (to connect pivot table in DB)
    public function developers()
    {
        return $this->belongsToMany(Developer::class);
    }

    // Multiple games belong to one exhibitor at gamescom
    public function exhibitors()
    {
        return $this->belongsToMany(Exhibition::class);
    }

    // Show only published Scope in where clause

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public static function recentGames($limit = 5)
    {
        return Game::published()
                   ->orderBy('published_at', 'DESC')
                   ->limit($limit)
                   ->get();
    }

    public function scopeSearch($query, $search_query)
    {
        $searchable = ['title', 'body'];

        foreach($searchable as $column) {
            $query->orWhere($column, 'like', '%' . $search_query . '%');
        }

        return $query;
    }

    public function getReleasedAttribute()
    {
        if(!is_null($this->released_at)) {

            $date = $this->released_at;
            $separator = '-';
            $d = explode($separator, $date);

            // If month (and day as well) are unkown, show only the year
            if($d[1] == "00") {
                return Carbon::CreateFromFormat("Y-m-d", $d[0] . '-' . '01-01')->format('Y');
            } else if($d[2] == "00") {
                return Carbon::CreateFromFormat("Y-m-d", $d[0] . '-' . $d[1] . '-01')->format('F Y');
            }

            return Carbon::CreateFromFormat("Y-m-d", $this->released_at)->format('j F Y');
        }
        return 'T.B.A.';
    }

    public function getReleasedAtDayAttribute()
    {
        if(!is_null($this->released_at)) {

            return Carbon::CreateFromFormat("Y-m-d", $this->released_at)->format('j');
        }
        return '00';
    }

    public function getReleasedAtMonthAttribute()
    {
        if(!is_null($this->released_at)) {

            return Carbon::CreateFromFormat("Y-m-d", $this->released_at)->format('M');
        }
        return '00';
    }

    public function RSSFeeds() {
        return $this->hasMany(RSSItem::class);
    }

    public function articles() {
        return $this->hasMany(Article::class);
    }

    // Many to many (to connect pivot table in DB)
    public function platforms() {
        return $this->belongsToMany(Platform::class);
    }

    // Many to many (to connect pivot table in DB)
    public function genres() {
        return $this->belongsToMany(Genre::class);
    }

    // Many to many (to connect pivot table in DB)
    public function series() {
        return $this->belongsToMany(Serie::class);
    }

    // Many to many (to connect pivot table in DB)
    public function releases() {
        return $this->hasMany(Release::class);
    }

    public function getBodyHtmlAttribute()
    {
        return $this->body;
    }

    public function getExcerptHtmlAttribute()
    {
        return e($this->excerpt);
    }

    public function introduction()
    {
        $genres = $this->santiziseListToString($this->genres);
        $developers = $this->santiziseListToString($this->developers);
        $publishers = $this->santiziseListToString($this->publishers);
        $series = $this->santiziseListToString($this->series);

        $string = $this->title . " is " . $this->aOrAn($genres) . " " . $genres . " game. ";
        if(!$this->developers->isEmpty() && !$this->publishers->isEmpty()) {
            if($developers === $publishers) {
                $string .= "The game is developed and published by " . $developers;
            } else {
                $string .= "The game is developed by " . $developers . " and published by " . $publishers;
            }

            if(!$this->series->isEmpty()) {
                $string .= " and is part of the " . $series . " series";
            }

            $string .= ". ";
        }
        if(!$this->developers->isEmpty() && $this->publishers->isEmpty()) {
            $string .= "The game is developed by " . $developers . ". ";
        }
        if($this->developers->isEmpty() && !$this->publishers->isEmpty()) {
            $string .= "The game is published by " . $publishers . ". ";
        }
        $string .= "The release date ";

        if($this->getReleasedAttribute() == "T.B.A.") {
            $string .= "has yet to be announced. ";
        } else {
            if (Carbon::now()->lt(Carbon::parse($this->getReleasedAttribute()))) {
                $string .= "will be " . $this->getReleasedAttribute() . ". ";
            } else {
                $string .= "was on " . $this->getReleasedAttribute() . ". ";
            }
        }

        return $string;
    }

    private function aOrAn($string)
    {
        if($string == "") {
            return "a";
        }

        $klinker = ['a', 'e', 'i', 'o', 'u'];

        if(in_array($string[0], $klinker)) {
            return "an";
        } else {
            return "a";
        }
    }

    public function santiziseListToString($array)
    {
        // If the array is empty, return
        if($array->isEmpty()){
            return "";
        }

        $string = "";

        foreach($array as $key => $value) {
            $string .= $value->title;

            if (count($array) > 1) {
                if ($key <= count($array) - 3) {
                    $string .= ', ';
                }

                if ($key == count($array) - 2) {
                    $string .= ' and ';
                }
            }
        }

        return $string;
    }
}

app/Http/Controllers/PlatformController.php
<?php

namespace App\Http\Controllers;

use App\Models\Platform;
use Illuminate\Http\Request;

class PlatformController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $platforms = Platform::orderBy('title', 'asc')->get();
        foreach($platforms as $key => $platform) {
            if ($platform['title'] === '---') {
                unset($platforms[$key]);
            }
        }

        return view('platform.index', compact('platforms'));
    }

    /**
     * Display the specified resource.
     *
     * @param Platform $platform
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Platform $platform)
    {

        return view('platform.show', compact('platform'));
    }
}

resources/views/platform/index.blade.php
@extends('layouts.master')

@section('seo')
    @component("components.seo", ["title" => __('breadcrumbs.platforms'), "url" => url("platforms"), "description" => 'A great number of contributors, exhibitors and platforms are represented at Gamescom. For as far is there each year an increasement in their numbers. '] )
    @endcomponent
@endsection

@section('content')

    <section id="featured_image_section">
        <div class="featured_image pinkpurple" style="background-image:url('https://www.gamescomevent.com/img/gamescom_17_010_010.jpg')"></div>
    </section>

    <div class="container show platform-show">
        <div class="row">
            <div class="col-md-12">

                {{-- Title --}}
                <h1>{{__('breadcrumbs.platforms')}}</h1>

                {{-- Breadcrumbs --}}
                @component('components.breadcrumbs', ['breadcrumbs' => ['platforms' => __('breadcrumbs.platforms')]])
                @endcomponent
                @foreach($platforms as $platform)
                    <a href="{{url('platforms/' . $platform->slug)}}">{{$platform->title}}</a> <br />
                @endforeach

            </div>
        </div>
    </div>

@endsection

resources/views/platform/show.blade.php
@extends('layouts.master')

@section('seo')
    @component("components.seo", ["title" => $platform->title, "url" => url("platforms/" . $platform->slug), "description" => $platform->excerpt] )
    @endcomponent
@endsection

@section('content')

    <section id="featured_image_section">
        <div class="featured_image greenblue" style="background-image:url('https://www.gamescomevent.com/img/gamescom_17_010_010.jpg')"></div>
    </section>

    <div class="container show platform-show">
        <div class="row">
            <div class="col-md-12">

                {{-- Title --}}
                <h1>{{$platform->title}}</h1>

                {{--Breadcrumbs--}}
                @component('components.breadcrumbs', ['breadcrumbs' => ['platforms' => __('breadcrumbs.platforms'), url("platforms/" . $platform->slug) => $platform->title]])
                @endcomponent

            </div>
            <div class="col-md-9">
                <p><strong>{!! $platform->excerpt !!}</strong></p>
                <br />
                <p>
                    {!! $platform->body_html !!}
                </p>
                @guest
                @else
                    <br><a href="{{ url("admin/platforms/" . $platform->slug . "/edit") }}">Edit</a><br><br>
                @endguest
            </div>

            <div class="col-md-3 sidebar">
                <h2>Overview</h2>
                <ul class="meta">
                    @if($platform->released == "T.B.A.")
                        <li><i class="fa fa-calendar" title="Release date"></i>Planned for <a href="#" title="{{$platform->released}}">{{$platform->released}}</a></li>
                    @else
                        @if(Carbon\Carbon::now()->lt(Carbon\Carbon::parse($platform->released)))
                            <li><i class="fa fa-calendar" title="Release date"></i>Planned for <a href="#" title="{{$platform->released}}">{{$platform->released}}</a></li>
                        @else
                            <li><i class="fa fa-calendar" title="Release date"></i>First released on <a href="#" title="{{$platform->released}}">{{$platform->released}}</a></li>
                        @endif
                    @endif
                </ul>
                @if(!$platform->games->isEmpty())

                <div class="horizontal-line"></div>

                <h2>All playable games</h2>
                <ul>
                    @foreach($platform->games as $game)
                        <li><a href="{{ url("games/" . $game->slug) }}">{{ $game->title }}</a></li>
                    @endforeach
                </ul>
                @endif


                {{--<h2>Recent news</h2>--}}
                {{--<ul>--}}
                    {{--@foreach($platform->articles as $article)--}}
                        {{--<li><a target="_blank" href="{{ url('article/' . $article->slug) }}">{{ $article->title }}</a></li>--}}
                    {{--@endforeach--}}
                {{--</ul>--}}
            </div>
        </div>
    </div>
@endsection