routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\ActivateController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ArticleController as BackendArticleController;
use App\Http\Controllers\Backend\ExhibitionController as BackendExhibitionController;
use App\Http\Controllers\Backend\GameController as BackendGameController;
use App\Http\Controllers\Backend\GenreController as BackendGenreController;
use App\Http\Controllers\Backend\PlatformController as BackendPlatformController;
use App\Http\Controllers\Backend\PublisherController as BackendPublisherController;
use App\Http\Controllers\Backend\RSSItemController;
use App\Http\Controllers\Backend\RSSItemController as BackendRSSItemController;
use App\Http\Controllers\Backend\RSSWebsiteController as BackendRSSWebsiteController;
use App\Http\Controllers\Backend\SerieController as BackendSerieController;
use App\Http\Controllers\Backend\UserController as BackendUserController;
use App\Http\Controllers\Backend\PageController as BackendPageController;
use App\Http\Controllers\DeveloperController;
use App\Http\Controllers\ExhibitionController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PlatformController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\RSSCrawlerController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin'], function() {

    $exceptShow = ['except' => [ 'show' ] ];

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('home');

    Route::resource('/articles', App\Http\Controllers\Backend\ArticleController::class);
    Route::resource('/developers', App\Http\Controllers\Backend\DeveloperController::class, $exceptShow);
    Route::resource('/exhibitions', BackendExhibitionController::class, $exceptShow);
    Route::post('/exhibitions/game/add', [BackendExhibitionController::class, 'save_exhibition_game']);
    Route::post('/exhibitions/game/update', [BackendExhibitionController::class, 'update_exhibition_game']);
    Route::resource('/games', BackendGameController::class, $exceptShow);
    Route::post('/games/ajax', [BackendGameController::class, 'ajax']);
    Route::resource('/genres', BackendGenreController::class, $exceptShow);
    Route::resource('/platforms', BackendPlatformController::class, $exceptShow);
    Route::resource('/publishers', BackendPublisherController::class, $exceptShow);
    Route::resource('/rssitems', BackendRSSItemController::class, $exceptShow);
    Route::resource('/rsswebsites', BackendRSSWebsiteController::class);
    Route::resource('/series', BackendSerieController::class)->parameters(['series' => 'serie']);;
    Route::resource('/users', BackendUserController::class, $exceptShow);
    Route::resource('/pages', BackendPageController::class)->parameters([
        'pages' => 'admin_pages'
    ]);

    Route::get('removeDuplicates', [RSSCrawlerController::class, 'removeDuplicates']);
    Route::get('games/recently-in-rss', [BackendGameController::class, 'recentlyInRSS']);
    Route::get('games/recently-in-rss/coupling', [BackendGameController::class, 'recentlyInRSSCoupling']);
    Route::get('games/find-publisher/{game}', [BackendGameController::class, 'findPublisher']);
    Route::get('games/find-developer/{game}', [BackendGameController::class, 'findDeveloper']);
    Route::get('games/create/{title}', [BackendGameController::class, 'create']);
    Route::get('games/enrich', [BackendGameController::class, 'enrich']);
    Route::get('/news', [BackendArticleController::class, 'index']);
    Route::get('publishers/create/{title}', [BackendPublisherController::class, 'create']);
    Route::get('rssitems/find-keywords', [BackendRSSItemController::class,'findKeywords']);
    Route::get('rssitems/suggest-game-title', [RSSCrawlerController::class, 'suggestGameTitle']);
    Route::get('rssitems/import',  [BackendRSSItemController::class,'import']);
    Route::get('rssitems/link',  [BackendRSSItemController::class,'link']);
    Route::get('rssitems/archive/{dateFrom}/{dateTo?}',  [BackendRSSItemController::class,'archive']);
});

// Sitemap
Route::get('/sitemap.xml', [SitemapController::class, 'index']);
Route::get('/sitemap', [SitemapController::class, 'index']);
Route::get('/sitemap/articles', [SitemapController::class, 'articles']);
Route::get('/sitemap/platforms', [SitemapController::class, 'platforms']);
Route::get('/sitemap/games', [SitemapController::class, 'games']);
Route::get('/sitemap/pages', [SitemapController::class, 'pages']);
Route::get('/rss', [SitemapController::class, 'rss']);

// Articles
Route::get('/news', [ArticleController::class, 'index']);
Route::get('/article/{article}', [ArticleController::class, 'show']);

// Publishers
Route::get('/publishers', [PublisherController::class, 'index']);
Route::get('/publishers/{publisher}', [PublisherController::class, 'show']);

// Developers
Route::get('/developers', [DeveloperController::class, 'index']);
Route::get('/developers/{developer}', [DeveloperController::class, 'show']);

// Platforms
Route::get('/platforms', [PlatformController::class, 'index']);
Route::get('/platforms/{platform}', [PlatformController::class, 'show']);


// Users
Route::get('/users/{user}', [UserController::class, 'show']);
Route::get('/members/{user}', [UserController::class, 'show']);

// Crawler
Route::get('/crawler/crawl', [RSSCrawlerController::class, 'crawl']);

// Games
Route::get('/games/list', [GameController::class, 'listed'])->name('games.list');
Route::get('/games/upcoming', [GameController::class, 'upcoming'])->name('games.upcoming');
Route::resource('/games', GameController::class)->only(['index', 'show'])->name('games', 'games.show');

// Search
Route::post('/search', [SearchController::class, 'index']);
Route::get('/search/{search}', [SearchController::class, 'results']);

// Authentication
Auth::routes();
Route::get('/validate', [ActivateController::class, 'index']);

// Other pages
Route::get('/', [PageController::class, 'home']);

// Very last routes for catching all pages
Route::get('/{exhibition}/lineup', [ExhibitionController::class, 'lineup']);
Route::get('/{exhibition}/exhibitors', [ExhibitionController::class, 'exhibitors']);

Route::get('/{slug}', function($slug) {

    $page = \App\Models\Page::where('slug', '=', $slug)->first();
    if($page != null) {
        $controller = app()->make('\App\Http\Controllers\PageController');
        return $controller->callAction('show', [$page]);
    }
    $exhibition = \App\Models\Exhibition::where('slug', '=', $slug)->first();
    if($exhibition != null) {
        $controller = app()->make('\App\Http\Controllers\ExhibitionController');
        return $controller->callAction('show', [$exhibition]);
    }

    if($exhibition == null && $page == null) {
        abort(404);
    }
});

app/Models/Developer.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Developer extends Model
{
    use HasFactory;

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'developers';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'image',
        'url',
        'found',
    ];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getDateAttribute()
    {
        return is_null($this->updated_at) ? '' : $this->updated_at->diffForHumans();
    }

    public function getFoundYmdAttribute()
    {
        return is_null($this->found) ? '' : str_replace(' 00:00:00', '', $this->found);
    }

    public function getFoundedAttribute()
    {
        if(!is_null($this->found)) {

            $date = $this->found;
            $separator = '-';
            $d = explode($separator, $date);
            $d[2] = explode(' ', $d[2])[0];

            // If month (and day as well) are unkown, show only the year
            if($d[1] == "00") {
                return Carbon::CreateFromFormat("Y-m-d", $d[0] . '-' . '01-01')->format('Y');
            } else if($d[2] == "00") {
                return Carbon::CreateFromFormat("Y-m-d", $d[0] . '-' . $d[1] . '-01')->format('F Y');
            }

            $dateText = Carbon::parse($this->found)->format('l jS \\of F Y');
            return "<a href='#' title='" . $dateText . "'>$d[0]</a>";
        }
        return 'Unkown.';
    }

    public function getBodyHtmlAttribute()
    {
        return $this->body;
    }

    public function getExcerptHtmlAttribute()
    {
        return e($this->excerpt);
    }

    // A developer has many games
    // Many to many (to connect pivot table in DB)
    public function games()
    {
        return $this->belongsToMany(Game::class);
    }

    public function exhibitor_games()
    {
        return $this->hasMany(Game::class, 'exhibitor_id', 'id');
    }

    public function exhibitionGame()
    {
        return $this->hasMany(ExhibitionGame::class, 'developer_id', 'id');
    }

    public function exhibition_booths()
    {
        return $this->hasMany(ExhibitionGame::class, 'developer_id', 'id');
    }

    public function exhibition_games()
    {
        return $this->belongsToMany(Game::class, 'exhibition_game',
            'developer_id', 'game_id');
    }

    public function exhibition_game()
    {
        return $this->belongsToMany(Game::class, 'exhibition_game',
            'developer_id', 'game_id');
    }

    public function games_for_gamescom_2025()
    {
        return $this->belongsToMany(Game::class, 'exhibition_game',
            'developer_id', 'game_id')->where('exhibition_game.exhibition_id', '=', 5);
    }
}

app/Models/Release.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Release extends Model
{

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'releases';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'game_id',
        'released_at',
        'console',
        'region',
        'edition',
    ];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    // Multiple games belong to multiple publishers
    // Many to many (to connect pivot table in DB)
    public function game()
    {
        return $this->hasOne(Game::class);
    }

    public function getReleasedAttribute()
    {
        if(!is_null($this->released_at)) {

            $date = $this->released_at;
            $separator = '-';
            $d = explode($separator, $date);

            // If month (and day as well) are unkown, show only the year
            if($d[1] == "00") {
                return Carbon::CreateFromFormat("Y-m-d", $d[0] . '-' . '01-01')->format('Y');
            } else if($d[2] == "00") {
                return Carbon::CreateFromFormat("Y-m-d", $d[0] . '-' . $d[1] . '-01')->format('F Y');
            }

            return Carbon::CreateFromFormat("Y-m-d", $this->released_at)->format('j F Y');
        }
        return 'T.B.A.';
    }

    public function getReleasedAtDayAttribute()
    {
        if(!is_null($this->released_at)) {

            return Carbon::CreateFromFormat("Y-m-d", $this->released_at)->format('j');
        }
        return '00';
    }

    public function getReleasedAtMonthAttribute()
    {
        if(!is_null($this->released_at)) {

            return Carbon::CreateFromFormat("Y-m-d", $this->released_at)->format('M');
        }
        return '00';
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Game;
use App\Models\RSSItem;
use App\Models\RSSWebsite;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $last_48_hours = Carbon::now()->subHours(48);

        // Get top 5 RSS Websites
        $rss_websites = RSSItem::select('rss_website_id', DB::raw("count(*) as count"))
            ->where('published_at', '>=', $last_48_hours)
            ->groupBy('rss_website_id')
            ->orderBy('count', 'desc')
            ->limit(5)
            ->get();

        // Get count of all rss_articles with a game_id
        $count_rss_articles_with_game_id = DB::table('rss_feeds')
                ->select(DB::raw("count(*) as count"))
                ->where([['game_id', '!=', null],['published_at', '>=', $last_48_hours]])
                ->get();

        // Get count of all rss_articles without a game_id
        $count_rss_articles_without_game_id = DB::table('rss_feeds')
                 ->select(DB::raw("count(rss_feeds.id) as count"))
                 ->where([['game_id', '=', null],['published_at', '>=', $last_48_hours]])
                 ->get();

        $count_rss_articles_with_film_in_title = DB::table('rss_feeds')
                ->select(DB::raw("count(rss_feeds.id) as count"))
                ->whereRaw('lower(rss_feeds.title) like (?)',["%film%"])
                ->where([['game_id', '=', null],['published_at', '>=', $last_48_hours]])
                ->get();

        $count_rss_articles_with_e3_in_title = DB::table('rss_feeds')
                ->select(DB::raw("count(rss_feeds.id) as count"))
                ->whereRaw('lower(rss_feeds.title) like (?)',["%e3%"])
                ->where([['game_id', '=', null],['published_at', '>=', $last_48_hours]])
                ->get();

        $count_rss_articles_with_gamescom_in_title = DB::table('rss_feeds')
                 ->select(DB::raw("count(rss_feeds.id) as count"))
                 ->whereRaw('lower(rss_feeds.title) like (?)',["%gamescom%"])
                 ->where([['game_id', '=', null],['published_at', '>=', $last_48_hours]])
                 ->get();

        $rss_top_5_games = Game::with(['RSSFeeds' => function($query) {
                        $query->where([['published_at', '>=', Carbon::now()->subHours(48)], ['game_id', '!=', null]]);
                     }])
                     ->get()
                     ->sortByDesc(function($games) {
                         return $games->RSSFeeds->count();
                     });

        // Reset keys for array
        $rss_top_5_games = $rss_top_5_games->values();


        return view('backend.dashboard', compact('rss_websites', 'count_rss_articles_with_game_id', 'count_rss_articles_without_game_id', 'rss_top_5_games', 'count_rss_articles_with_film_in_title', 'count_rss_articles_with_e3_in_title', 'count_rss_articles_with_gamescom_in_title'));
    }
}

resources/views/backend/developer/create.blade.php
@extends('backend.layouts.master')

@section('content')

    <section id="featured_line_section">
        <div class="featured_line greenblue"></div>
    </section>

    <div class="container backend-main">
        <div class="row">
            <div class="col-md-12">

                {{-- Title --}}
                <h1>Add a developer</h1>

                {{--Breadcrumbs--}}
                @component('backend.components.breadcrumbs', ['breadcrumbs' => ['admin/developers' => 'developers', 'admin/developers/create' => 'Add a developer']])
                @endcomponent

            </div>

            <form method="POST" action="{{url('/admin/developers')}}">

                {{--Load the form--}}
                @component('backend.developer.form', compact('developer'))
                @endcomponent

            </form>

        </div>
    </div>
@endsection

resources/views/backend/developer/edit.blade.php
@extends('backend.layouts.master')

@section('content')

    <section id="featured_line_section">
        <div class="featured_line greenblue"></div>
    </section>

    <div class="container backend-main">
        <div class="row">
            <div class="col-md-12">

                {{-- Title --}}
                <h1>Edit "{{$developer->title}}"</h1>

                {{--Breadcrumbs--}}
                @component('backend.components.breadcrumbs', ['breadcrumbs' => ['admin/developers' => 'developers', 'admin/developers/' . $developer->slug . '/edit' => 'Edit "' . $developer->title . '"']])
                @endcomponent
            </div>

            <form method="POST" action="{{url('/admin/developers/' . $developer->slug)}}">

                {{--Set the post method to patch--}}
                {{ method_field('PATCH') }}

                {{--Load the form--}}
                @component('backend.developer.form', compact('developer'))
                @endcomponent

            </form>

        </div>
    </div>
@endsection

resources/views/backend/developer/form.blade.php
<div class="col-md-12">
    @include('backend.components.error')
</div>

<div class="col-md-9">

    {{ csrf_field() }}

    <div class="form-group">
        <label for="title">Title *</label><br>
        <input type="text" class="form-control" id="title" name="title" required autocomplete="off" value="{{ $developer->title }}">
    </div>

    <div class="form-group">
        <label for="slug">Slug *</label><br>
        <input type="text" class="form-control" id="slug" name="slug" required  autocomplete="off" value="{{ $developer->slug }}">
    </div>

    <div class="form-group">
        <label for="excerpt">Excerpt</label><br>
        <textarea type="text" class="form-control tinymce-editor" id="excerpt" name="excerpt" autocomplete="off">{{ $developer->excerpt }}</textarea>
    </div>

    <div class="form-group">
        <label for="body">Body</label><br>
        <textarea type="text" class="form-control tinymce-editor" id="body" name="body" autocomplete="off">{{ $developer->body }}</textarea>
    </div>

</div>

<div class="col-md-3">

    <div class="form-group">
        <label for="image">Image</label><br>
        <input type="text" class="form-control" id="image" name="image" autocomplete="off" value="{{ $developer->image }}">
    </div>

    <div class="form-group">
        <label for="url">url</label><br>
        <input type="text" class="form-control" id="url" name="url" autocomplete="off" value="{{ $developer->url }}">
    </div>

    <div class="form-group">
        <label for="found">found</label><br>
        <span class="note"><strong>note:</strong> "2018-00-00" notes as "in 2018"</span>
        <input type="text" class="form-control" id="found" name="found" autocomplete="off" value="{{ $developer->found_ymd }}">
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary button-full">Save</button>
    </div>

</div>

{{--jQuery--}}
<script type="text/javascript" src="//code.jquery.com/jquery-1.12.3.min.js"></script>

{{-- jQuery UI --}}
<script type="text/javascript" src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

{{--Select 2--}}
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $( function() {

        // Set slug
        $('#title').change( function() {
            var sluggie = slug($('#title').val());

            $('#slug').val(sluggie);

        });
    });

    var slug = function(str) {
        str = str.replace(/^\s+|\s+$/g, ''); // trim
        str = str.toLowerCase();

        // remove accents, swap ñ for n, etc
        var from = "ÁÄÂÀÃÅČÇĆĎÉĚËÈÊẼĔȆÍÌÎÏŇÑÓÖÒÔÕØŘŔŠŤÚŮÜÙÛÝŸŽáäâàãåčçćďéěëèêẽĕȇíìîïňñóöòôõøðřŕšťúůüùûýÿžþÞĐđßÆa·/_,:;";
        var to   = "AAAAAACCCDEEEEEEEEIIIINNOOOOOORRSTUUUUUYYZaaaaaacccdeeeeeeeeiiiinnooooooorrstuuuuuyyzbBDdBAa------";
        for (var i=0, l=from.length ; i<l ; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
        }

        str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
            .replace(/\s+/g, '-') // collapse whitespace and replace by -
            .replace(/-+/g, '-'); // collapse dashes

        return str;
    };

    $(document).ready(function() {
        $('.js-example-basic-multiple').select2({
            tags: true
        });
    });
</script>

resources/views/backend/developer/index.blade.php
@extends('backend.layouts.master')

@section('seo')
    @component("components.seo", ["title" => "Developers overview", "url" => url('admin/developers'), "description" => "Overview of all the developers on Enzow.org"] )
    @endcomponent
@endsection

@section('content')

    <section id="featured_line_section">
        <div class="featured_line greenblue"></div>
    </section>

    <div class="container backend-main">
        <div class="row">
            <div class="col-md-12">

                {{-- Title --}}
                <h1>Developers</h1>

                {{--Breadcrumbs--}}
                @component('backend.components.breadcrumbs', ['breadcrumbs' => ['admin/developers' => 'Developers']])
                @endcomponent

                <a class="button button-primary" href="{{ url('admin/developers/create')}}">Add a developer</a><br><br>

                <script type="text/javascript" language="javascript" src="//code.jquery.com/jquery-3.4.1.slim.min.js"></script>
                <script type="text/javascript" language="javascript" src="{{asset('js/dataTables.js')}}"></script>
                <script type="text/javascript" language="javascript" class="init">
                    $(document).ready(function() {
                        $('#example').DataTable({

                            "paging":       true,
                            "pagingType":   "numbers",
                            "lengthMenu":   [[100, 250, -1], [100, 250, "All"]],
                            "ordering":     true,
                            "info":         false,
                            "searching":    true

                        });
                    } );
                </script>

                <table id="example" class="display" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th class="align-center-center">
                            <input type="checkbox" title="selectAll">
                        </th>
                        <th>Title</th>
                        <th class="align-right not-on-mobile"></th>
                        <th class="align-right">Tools</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($developers as $developer)
                        <tr>
                            <td class="align-center-center">
                                <input type="checkbox" title="id" value="{{$developer->id}}"/>
                            </td>
                            <td><a href="{{url('developers/' . $developer->slug)}}">{{$developer->title}}</a><br><span class="tags"></span></td>
                            <td class="align-right developer-attributes not-on-mobile">
                                <a @if($developer->released != "") class="filled-attribute" @endif title="{{$developer->released}}"><i class="fa fa-calendar"></i></a>&nbsp;
                                {{--<a @if(!$developer->genres->isEmpty()) class="filled-attribute" @endif title="Genres: @foreach($developer->genres as $genreA) {{$genreA->title}}, @endforeach"><i class="fa fa-book"></i></a>&nbsp;--}}
                                <a @if(!$developer->games->isEmpty()) class="filled-attribute" @endif title="Games: {{count($developer->games)}}"><i class="fa fa-gamepad"></i></a>&nbsp;
                            </td>
                            <td class="align-right">
                                <a href="{{url('/developers/' . $developer->slug)}}"><i class="fa fa-window-maximize"></i></a> &nbsp;
                                <a href="{{url('/admin/developers/' . $developer->slug . '/edit')}}"><i class="fa fa-pencil"></i></a> &nbsp;
                                {{ Form::open(array('url' => url('/admin/developers/' . $developer->slug), "class" => 'delete-row' )) }}
                                {{ Form::hidden('_method', 'DELETE') }}
                                <button type='submit' value="delete"><i class="fa fa-trash"></i></button>
                                {{ Form::close() }}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection